### ISSUE TITLE
date-fnsに乗り換える

### ISSUE THREAD

**Issue by ncaq** [ncaq/goodbye-rfc-2822-date-time#28]
momentから乗り換えるだけでそれなりに軽量化するのでは

**Comment by ncaq** [comment]
容量系全体に言えますけどそこまで容量もんだいになってないし無理に乗り換えなくても良さそう

**Comment by munierujp** [comment]
Moment.jsは2020年9月15日頃、公式にレガシーなプロジェクトであるとされたので、アクティブにメンテナンスされているdate-fns（あるいはDay.jsなど）のようなライブラリに移行するのは良い選択だと思われます。

>We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.

https://momentjs.com/docs/#/-project-status/
